services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./funATI/media:/app/funATI/media
      - ./funATI/db.sqlite3:/app/funATI/db.sqlite3
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/app/healthcheck.sh"]
      interval: 90s
      timeout: 45s
      retries: 3
      start_period: 180s
  