# Generated by Django 5.2.3 on 2025-08-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funATIAPP', '0011_alter_usersettings_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='funATIAPP.profile'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10),
        ),
    ]
